"""
StaffWorkflow — Phase 1 Capability Workflow for Atlas Staff.

Agents call staff_workflow() instead of constructing raw mcp_read/execute_transaction calls.

Covers:
  - get schedule
  - get today's schedule
  - get next customer
  - get customer history
  - get customer preferences
  - get staff revenue
  - get staff performance
  - get pending appointments
  - create leave request
  - send customer reminders
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Optional

from application.services.entity_resolver_service import resolve_relative_date

logger = logging.getLogger(__name__)


class StaffWorkflow:
    """
    Phase 1 workflow encapsulating all staff productivity operations for Atlas Staff.
    """

    @staticmethod
    def get_schedule(
        staff_id: Optional[str] = None,
        date: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Retrieve the staff member's appointment schedule for a specific date."""
        logger.info("[StaffWorkflow] get_schedule: staff=%s date=%s", staff_id, date)
        try:
            resolved_date = resolve_relative_date(date) if date else None
            from application.services.staff_service import get_schedule
            return {"success": True, "result": get_schedule(staff_id=staff_id, date_str=resolved_date)}
        except Exception as exc:
            logger.error("[StaffWorkflow] get_schedule failed: %s", exc)
            return {"success": False, "error": str(exc)}

    @staticmethod
    def get_today_schedule(staff_id: Optional[str] = None) -> Dict[str, Any]:
        """Retrieve today's full appointment schedule for a staff member."""
        logger.info("[StaffWorkflow] get_today_schedule: staff=%s", staff_id)
        try:
            from application.services.staff_service import get_today_schedule
            return {"success": True, "result": get_today_schedule(staff_id=staff_id)}
        except Exception as exc:
            logger.error("[StaffWorkflow] get_today_schedule failed: %s", exc)
            return {"success": False, "error": str(exc)}

    @staticmethod
    def get_next_customer(staff_id: Optional[str] = None) -> Dict[str, Any]:
        """Get details about the next upcoming customer for a staff member."""
        logger.info("[StaffWorkflow] get_next_customer: staff=%s", staff_id)
        try:
            from application.services.staff_service import get_next_customer
            return {"success": True, "result": get_next_customer(staff_id=staff_id)}
        except Exception as exc:
            logger.error("[StaffWorkflow] get_next_customer failed: %s", exc)
            return {"success": False, "error": str(exc)}

    @staticmethod
    def get_customer_history(customer_name: str) -> Dict[str, Any]:
        """Get booking history for a specific customer by name."""
        logger.info("[StaffWorkflow] get_customer_history: customer=%s", customer_name)
        try:
            from application.services.staff_service import get_customer_history
            return {"success": True, "result": get_customer_history(customer_name=customer_name)}
        except Exception as exc:
            logger.error("[StaffWorkflow] get_customer_history failed: %s", exc)
            return {"success": False, "error": str(exc)}

    @staticmethod
    def get_customer_preferences(customer_name: str) -> Dict[str, Any]:
        """Get service and styling preferences for a specific customer."""
        logger.info("[StaffWorkflow] get_customer_preferences: customer=%s", customer_name)
        try:
            from application.services.staff_service import get_customer_preferences
            return {"success": True, "result": get_customer_preferences(customer_name=customer_name)}
        except Exception as exc:
            logger.error("[StaffWorkflow] get_customer_preferences failed: %s", exc)
            return {"success": False, "error": str(exc)}

    @staticmethod
    def get_staff_revenue(staff_id: Optional[str] = None) -> Dict[str, Any]:
        """Retrieve revenue generated by a staff member."""
        logger.info("[StaffWorkflow] get_staff_revenue: staff=%s", staff_id)
        try:
            from application.services.staff_service import get_staff_revenue
            return {"success": True, "result": get_staff_revenue(staff_id=staff_id)}
        except Exception as exc:
            logger.error("[StaffWorkflow] get_staff_revenue failed: %s", exc)
            return {"success": False, "error": str(exc)}

    @staticmethod
    def get_staff_performance(staff_id: Optional[str] = None) -> Dict[str, Any]:
        """Get KPI performance metrics for a staff member."""
        logger.info("[StaffWorkflow] get_staff_performance: staff=%s", staff_id)
        try:
            from application.services.staff_service import get_staff_performance
            return {"success": True, "result": get_staff_performance(staff_id=staff_id)}
        except Exception as exc:
            logger.error("[StaffWorkflow] get_staff_performance failed: %s", exc)
            return {"success": False, "error": str(exc)}

    @staticmethod
    def get_pending_appointments(staff_id: Optional[str] = None) -> Dict[str, Any]:
        """Get all pending (unconfirmed) appointments for a staff member."""
        logger.info("[StaffWorkflow] get_pending_appointments: staff=%s", staff_id)
        try:
            from application.services.staff_service import get_pending_appointments
            return {"success": True, "result": get_pending_appointments(staff_id=staff_id)}
        except Exception as exc:
            logger.error("[StaffWorkflow] get_pending_appointments failed: %s", exc)
            return {"success": False, "error": str(exc)}

    @staticmethod
    def create_leave_request(
        staff_id: Optional[str] = None,
        leave_date: Optional[str] = None,
        reason: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Log a leave request for a staff member."""
        logger.info(
            "[StaffWorkflow] create_leave_request: staff=%s date=%s", staff_id, leave_date
        )
        try:
            resolved_date = resolve_relative_date(leave_date) if leave_date else None
            from application.services.staff_service import create_leave_request
            return {"success": True, "result": create_leave_request(
                staff_id=staff_id,
                leave_date=resolved_date or leave_date,
                reason=reason,
            )}
        except Exception as exc:
            logger.error("[StaffWorkflow] create_leave_request failed: %s", exc)
            return {"success": False, "error": str(exc)}

    @staticmethod
    def send_customer_reminders(staff_id: Optional[str] = None) -> Dict[str, Any]:
        """Dispatch appointment reminders to all of a stylist's upcoming customers."""
        logger.info("[StaffWorkflow] send_customer_reminders: staff=%s", staff_id)
        try:
            from application.services.staff_service import send_customer_reminders
            return {"success": True, "result": send_customer_reminders(staff_id=staff_id)}
        except Exception as exc:
            logger.error("[StaffWorkflow] send_customer_reminders failed: %s", exc)
            return {"success": False, "error": str(exc)}

